language: python

env:
  - TOXENV=doc
  - TOXENV=rtd
  - TOXENV=py27

before_install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq swig
  - if [ $TOXENV == "doc" ]; then sudo apt-get install -qq libfreetype6-dev libpng12-dev; fi
  - if [ $TOXENV == "doc" -o $TOXENV == "rtd" ]; then sudo apt-get install graphviz; fi

install:
  - pip install --upgrade setuptools
  - pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/numpy/numpy-1.8.1-cp27-none-linux_x86_64.whl
  - pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/scipy/scipy-0.14.0-cp27-none-linux_x86_64.whl
  - export PYTHONPATH=$PWD/tmp
  # need matplotlib in "doc"
  - if [ $TOXENV == "doc" ]; then pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/matplotlib/matplotlib-1.3.1-cp27-none-linux_x86_64.whl; fi
  - pip install tox

script:
  - tox

