language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq swig

install:
  - pip install --upgrade setuptools
  - pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/numpy/numpy-1.8.1-cp27-none-linux_x86_64.whl
  - pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/scipy/scipy-0.14.0-cp27-none-linux_x86_64.whl
  - pip install tox
  - export PYTHONPATH=$PWD/tmp

script:
  - tox

