language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export TOXENV="doc,rtd,py27"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export TOXENV="py34"; fi

  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq swig libfreetype6-dev libpng12-dev graphviz

install:
  - pip install --upgrade setuptools
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/numpy/numpy-1.8.1-cp27-none-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/scipy/scipy-0.14.0-cp27-none-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/numpy/numpy-1.9.1-cp34-cp34m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/scipy/scipy-0.14.0-cp34-cp34m-linux_x86_64.whl; fi
    
  - export PYTHONPATH=$PWD/tmp
  # need matplotlib in "doc"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -t $PWD/tmp https://dl.dropboxusercontent.com/u/9313631/wheelhouse/matplotlib/matplotlib-1.3.1-cp27-none-linux_x86_64.whl; fi

  - pip install tox

script:
  - tox

